name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: SantiagoRomero2707/shared-workflows/.github/workflows/build.yml@master
    with:
      java-version: '17'
      skip-tests: true

  deploy:
    needs: build
    uses: SantiagoRomero2707/shared-workflows/.github/workflows/deploy.yml@master
    with:
      java-version: '17'
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      environment: production
    secrets:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}